### ISSUE TITLE
Issue with bootstrap_install.ps1

### ISSUE THREAD

**Issue by al-mat** [GoogleCloudPlatform/compute-image-tools#1702]
I've got this

PS C:\Users\alissonmatos\Downloads> ./bootstrap_install.ps1

    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          27/07/2021    20:59                builder

    Directory: C:\builder\components

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          27/07/2021    20:59                updates
d----          27/07/2021    20:59                drivers
Failed to retrieve value for uefi-build.
Exception caught in script:
At C:\Users\alissonmatos\Downloads\bootstrap_install.ps1:257 char:3
+   $script:uefi = (Get-MetadataValue -key 'uefi-build').ToLower() -eq  …
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Message: You cannot call a method on a null-valued expression.
Windows build failed.

**Comment by bkatyl** [comment]
It looks like the script wasn't able to communicate with the metadata server. Since the error message shows a users directory, can you share if this was running in a GCE instance?
Also did you start of the build process using daisy as we populate those metadata keys in the image creation workflows?

If daisy wasn't used then you can find documentation on how to use it to invoke the build process at https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/daisy_workflows/image_build/windows#starting-a-build-workflow

**Comment by al-mat** [comment]
Sorry... now I've seen my mistake. I forgot to do some parts. Thanks for the help.
