### ISSUE TITLE
Python coding style

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-tools#352]
Hi,

Is there a document describing the coding style that should be used? The link pointed by CONTRIBUTING.md doesn't describe the style :(

**Comment by zmarano** [comment]
@illfelder

**Comment by illfelder** [comment]
We don't currently have a doc describing the coding style. It's mostly the same as the code style of compute-image-packages except with 79 character limits... due to flake8 not supporting line length checks other than that.

Here's a command you can run to lint your code locally.
`flake8 --ignore E111,E114,E121,E125,E128,E129 --import-order-style=google`
