### ISSUE TITLE
GuestOsFeatures documentation has `[]string]`

### ISSUE THREAD

**Issue by jsoref** [GoogleCloudPlatform/compute-image-tools#365]
https://github.com/GoogleCloudPlatform/compute-image-tools/blob/de0676695cc81af8f582db9a703e5e7c7a6a995f/docs/daisy-workflow-config-spec.md#L233

**Comment by jsoref** [comment]
Based on `Metadata`, it appears the right answer is `map[string]string`.

I might send a PR for this. (I'm still trying to figure out if I can use this tool to achieve my task...)

**Comment by zmarano** [comment]
Speaking of, what is your task? Maybe we can help you answer that question.

**Comment by zmarano** [comment]
+ @adjackura

**Comment by jsoref** [comment]
Automating the deployment of VMs to Google cloud. We have a Jenkins in GCE which automatically starts build nodes there which build our software.

For this project, I want to create modern "immutable" systems, so ideally when I start one, we give it some configuration, but it already has our software and the required system software enabled and mostly configured.

I've looked into chef/puppet/ansible and they're both painful to write and really not helpful, since the goal is that systems be immutable.

I'm considering using Terraform as the orchestrator.

**Comment by zmarano** [comment]
Cool, depending exactly what you mean by immutable systems Daisy can probably help you here.

If you want to build GCE images that have your software pre-installed to then use to deploy instances that is absolutely what Daisy can do. Generally you would build your image using one of the GCE base images and bootstrap what you want and what you want configured on it. Technically, because Daisy is just an API workflow client, it can actually deploy instances from your images as well but that doesn't quite handle ongoing orchestration as such. It is useful for testing the image you just built however.

A conceivable workflow is:
derivative image build -> deploy to test instance -> run tests, on pass -> publish to production project/family for use with Terraform

**Comment by adjackura** [comment]
[]string is the correct type (the ] on the end is a typo).

You can specify GuestOSFeatures as a a simple list of strings:
"GuestOsFeatures": ["VIRTIO_SCSI_MULTIQUEUE", "MULTI_IP_SUBNET"],

or you can use the more complex system the api uses:
"GuestOsFeatures": [
  {
    "type": "VIRTIO_SCSI_MULTIQUEUE"
  },
  {
    "type": "MULTI_IP_SUBNET"
  }
],
